// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Semicolon.OnlineJudge.Data;

namespace Semicolon.OnlineJudge.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191214152122_AddEmailToUserDb")]
    partial class AddEmailToUserDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Semicolon.OnlineJudge.Models.Problemset.JudgeProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemoryLimit")
                        .HasColumnType("REAL");

                    b.Property<string>("TestDatas")
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeLimit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("JudgeProfile");
                });

            modelBuilder.Entity("Semicolon.OnlineJudge.Models.Problemset.PassRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Pass")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Submit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PassRate");
                });

            modelBuilder.Entity("Semicolon.OnlineJudge.Models.Problemset.Problem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExampleDataId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("JudgeProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PassRateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExampleDataId");

                    b.HasIndex("JudgeProfileId");

                    b.HasIndex("PassRateId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("Semicolon.OnlineJudge.Models.Problemset.TestData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Input")
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestData");
                });

            modelBuilder.Entity("Semicolon.OnlineJudge.Models.User.OJUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemsPassedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OJUsers");
                });

            modelBuilder.Entity("Semicolon.OnlineJudge.Models.Problemset.Problem", b =>
                {
                    b.HasOne("Semicolon.OnlineJudge.Models.Problemset.TestData", "ExampleData")
                        .WithMany()
                        .HasForeignKey("ExampleDataId");

                    b.HasOne("Semicolon.OnlineJudge.Models.Problemset.JudgeProfile", "JudgeProfile")
                        .WithMany()
                        .HasForeignKey("JudgeProfileId");

                    b.HasOne("Semicolon.OnlineJudge.Models.Problemset.PassRate", "PassRate")
                        .WithMany()
                        .HasForeignKey("PassRateId");
                });
#pragma warning restore 612, 618
        }
    }
}
